//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocMAH.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocMAH.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @databaseName NVARCHAR(128)
        ///SET @databaseName = &apos;docmahUnitTests&apos;
        ///
        ///IF (
        ///	EXISTS(
        ///		SELECT name 
        ///		FROM master.dbo.sysdatabases 
        ///		WHERE &apos;[&apos; + name + &apos;]&apos; = @databaseName
        ///			OR name = @databaseName
        ///	)
        ///) BEGIN
        ///	ALTER DATABASE docmahUnitTests SET SINGLE_USER WITH ROLLBACK IMMEDIATE
        ///
        ///	DROP DATABASE docmahUnitTests
        ///END.
        /// </summary>
        internal static string Database_Drop {
            get {
                return ResourceManager.GetString("Database_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @databaseName NVARCHAR(128)
        ///SET @databaseName = &apos;docmahUnitTests&apos;
        ///
        ///IF (
        ///	EXISTS(
        ///		SELECT name 
        ///		FROM master.dbo.sysdatabases 
        ///		WHERE &apos;[&apos; + name + &apos;]&apos; = @databaseName
        ///			OR name = @databaseName
        ///	)
        ///) BEGIN
        ///	DROP DATABASE docmahUnitTests
        ///END
        ///
        ///CREATE DATABASE docmahUnitTests.
        /// </summary>
        internal static string Database_Initialize {
            get {
                return ResourceManager.GetString("Database_Initialize", resourceCulture);
            }
        }
    }
}
