//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocMAH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocMAH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** Namespace **/
        ///var DMH = DMH || {};
        ///
        ////** Constants and Singletons **/
        ///DMH.PageTypes = function () {
        ///
        ///	//** Public Fields **
        ///	this.FirstTimePage = 1;
        ///	this.DocumentationPage = 2;
        ///
        ///	// Return singleton.
        ///	return this;
        ///}();
        ///
        ///DMH.HistoryState = function () {
        ///	this.Replace = 1;
        ///	this.Push = 2;
        ///	this.Pop = 3;
        ///
        ///	return this;
        ///}();
        ///
        ///DMH.Urls = function () {
        ///
        ///	// ** Public Fields **
        ///	this.DeletePage = &apos;/help.axd?m=DeletePage&apos;;
        ///	this.GenerateInstallScript = &apos;/help.axd?m=GenerateInstallScrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHJavaScript {
            get {
                return ResourceManager.GetString("DocMAHJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var DMH=DMH||{};DMH.PageTypes=function(){return this.FirstTimePage=1,this.DocumentationPage=2,this}();DMH.HistoryState=function(){return this.Replace=1,this.Push=2,this.Pop=3,this}();DMH.Urls=function(){return this.DeletePage=&quot;/help.axd?m=DeletePage&quot;,this.GenerateInstallScript=&quot;/help.axd?m=GenerateInstallScript&quot;,this.MovePage=&quot;/help.axd?m=MovePage&quot;,this.NavigateDocumentation=&quot;/help.axd?m=DocumentationPage&quot;,this.ReadApplicationSettings=&quot;/help.axd?m=ReadApplicationSettings&quot;,this.ReadPage=&quot;/help.axd?m=ReadPage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHJavaScript_min {
            get {
                return ResourceManager.GetString("DocMAHJavaScript_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* comment to fix less compiling (https://github.com/madskristensen/WebEssentials2013/issues/1696)*/
        ////******	Custom JSTree Node Icons ******/
        ///.jstree-default .jstree-node.jstree-closed &gt; i.jstree-icon {
        ///  background-image: url(&apos;data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHStyles {
            get {
                return ResourceManager.GetString("DocMAHStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jstree-default .jstree-node.jstree-closed&gt;i.jstree-icon{background-image:url(&apos;data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkNhcGFfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHStyles_min {
            get {
                return ResourceManager.GetString("DocMAHStyles_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;/help.axd?m=CSS&quot; rel=&quot;stylesheet&quot; /&gt;.
        /// </summary>
        internal static string Html_CssLink {
            get {
                return ResourceManager.GetString("Html_CssLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;dmh-&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;[TITLE]&lt;/title&gt;
        ///	[JSTREECSS]
        ///	&lt;link href=&quot;/help.axd?m=CSS&quot; rel=&quot;stylesheet&quot; /&gt;
        ///	[CUSTOMCSS]
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div id=&quot;dmhDocToolBar&quot;&gt;
        ///		&lt;h3&gt;Edit Tools&lt;/h3&gt;
        ///		&lt;div class=&quot;dmhButtonBar&quot;&gt;
        ///			&lt;div id=&quot;dmhGenerateInstallScriptButton&quot; class=&quot;dmhButton dmhButtonSmall&quot;&gt;Generate Install Scripts&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;dmhDocToolBarBreak&quot;&gt;&lt;/div&gt;
        ///		&lt;div id=&quot;dmhStatusBar&quot;&gt;
        ///			&lt;div id=&quot;dmhStatusMessage&quot;&gt;&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;dmhCommonTools&quot;&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Documentation {
            get {
                return ResourceManager.GetString("Html_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html class=&quot;dmh-&quot;&gt;&lt;head&gt;&lt;title&gt;[TITLE]&lt;/title&gt;[JSTREECSS]&lt;link href=&quot;/help.axd?m=CSS&quot; rel=&quot;stylesheet&quot;&gt;[CUSTOMCSS]&lt;/head&gt;&lt;body&gt;&lt;div id=&quot;dmhDocToolBar&quot;&gt;&lt;h3&gt;Edit Tools&lt;/h3&gt;&lt;div class=&quot;dmhButtonBar&quot;&gt;&lt;div id=&quot;dmhGenerateInstallScriptButton&quot; class=&quot;dmhButton dmhButtonSmall&quot;&gt;Generate Install Scripts&lt;/div&gt;&lt;/div&gt;&lt;div id=&quot;dmhDocToolBarBreak&quot;&gt;&lt;/div&gt;&lt;div id=&quot;dmhStatusBar&quot;&gt;&lt;div id=&quot;dmhStatusMessage&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;div id=&quot;dmhCommonTools&quot;&gt;&lt;div class=&quot;dmhFormRow&quot;&gt;&lt;label for=&quot;dmhIsHidden&quot;&gt;Hide Page&lt;/label&gt; &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Documentation_min {
            get {
                return ResourceManager.GetString("Html_Documentation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhCreateHelpButton&quot; class=&quot;dmh- dmhButton&quot;&gt;Create Help Page&lt;/div&gt;
        ///&lt;div id=&quot;dmhFirstTimeEdit&quot; class=&quot;dmh- dmhDialog&quot;&gt;
        ///	&lt;div class=&quot;dmhDialogTitle&quot;&gt;Create Help Page&lt;/div&gt;
        ///	&lt;div class=&quot;dmhDialogContent&quot;&gt;
        ///		&lt;div class=&quot;dmhFormRow&quot;&gt;
        ///			&lt;label for=&quot;dmhFirstTimeEditTitle&quot;&gt;Help Title&lt;/label&gt;
        ///			&lt;input id=&quot;dmhFirstTimeEditTitle&quot; type=&quot;text&quot; /&gt;
        ///			&lt;div class=&quot;dmhFieldHelp&quot;&gt;Required&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div class=&quot;dmhFormRow&quot;&gt;
        ///			&lt;label for=&quot;dmhFirstTimeEditMatchUrls&quot;&gt;Match Urls&lt;/label&gt;
        ///			&lt;input id= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeEdit {
            get {
                return ResourceManager.GetString("Html_FirstTimeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhCreateHelpButton&quot; class=&quot;dmh- dmhButton&quot;&gt;Create Help Page&lt;/div&gt;&lt;div id=&quot;dmhFirstTimeEdit&quot; class=&quot;dmh- dmhDialog&quot;&gt;&lt;div class=&quot;dmhDialogTitle&quot;&gt;Create Help Page&lt;/div&gt;&lt;div class=&quot;dmhDialogContent&quot;&gt;&lt;div class=&quot;dmhFormRow&quot;&gt;&lt;label for=&quot;dmhFirstTimeEditTitle&quot;&gt;Help Title&lt;/label&gt; &lt;input id=&quot;dmhFirstTimeEditTitle&quot; type=&quot;text&quot;&gt;&lt;div class=&quot;dmhFieldHelp&quot;&gt;Required&lt;/div&gt;&lt;/div&gt;&lt;div class=&quot;dmhFormRow&quot;&gt;&lt;label for=&quot;dmhFirstTimeEditMatchUrls&quot;&gt;Match Urls&lt;/label&gt; &lt;input id=&quot;dmhFirstTimeEditMatchUrls&quot; type=&quot;text&quot;&gt;&lt;div  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeEdit_min {
            get {
                return ResourceManager.GetString("Html_FirstTimeEdit_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhModalMask&quot; class=&quot;dmh-&quot;&gt;&lt;/div&gt;
        ///&lt;div id=&quot;dmhFirstTimeView&quot; class=&quot;dmh- dmhDialog&quot;&gt;
        ///	&lt;div&gt;
        ///		&lt;div id=&quot;dmhShowDocumentationButton&quot; title=&quot;View full documentation&quot;&gt;
        ///			&lt;svg version=&quot;1.1&quot; id=&quot;dmhDocumentationIcon&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; x=&quot;0px&quot; y=&quot;0px&quot; width=&quot;50px&quot;
        ///				 height=&quot;50px&quot; viewBox=&quot;0 0 50 50&quot; enable-background=&quot;new 0 0 50 50&quot; xml:space=&quot;preserve&quot;&gt;
        ///			&lt;g id=&quot;_x38_7&quot;&gt;
        ///			&lt;g&gt;
        ///			&lt;path d=&quot;M12.03,21.967c-1.318,0-1.318,2.047,0,2.047c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeView {
            get {
                return ResourceManager.GetString("Html_FirstTimeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhModalMask&quot; class=&quot;dmh-&quot;&gt;&lt;/div&gt;&lt;div id=&quot;dmhFirstTimeView&quot; class=&quot;dmh- dmhDialog&quot;&gt;&lt;div&gt;&lt;div id=&quot;dmhShowDocumentationButton&quot; title=&quot;View full documentation&quot;&gt;&lt;svg version=&quot;1.1&quot; id=&quot;dmhDocumentationIcon&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; x=&quot;0px&quot; y=&quot;0px&quot; width=&quot;50px&quot; height=&quot;50px&quot; viewBox=&quot;0 0 50 50&quot; enable-background=&quot;new 0 0 50 50&quot; xml:space=&quot;preserve&quot;&gt;&lt;g id=&quot;_x38_7&quot;&gt;&lt;g&gt;&lt;path d=&quot;M12.03,21.967c-1.318,0-1.318,2.047,0,2.047c5.249,0,10.497,0,15.746,0c1.319,0,1.319-2.047,0-2.047
        ///												C22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeView_min {
            get {
                return ResourceManager.GetString("Html_FirstTimeView_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/help.axd?m=JavaScript&quot; type=&quot;application/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&quot;application/javascript&quot;&gt;
        ///	var applicationSettings = [APPLICATIONSETTINGSJSON];
        ///	var page = [PAGEJSON];
        ///	var userPageSettings = [USERPAGESETTINGSJSON];
        ///	$(function () {
        ///		var firstTimeEdit;
        ///		if (applicationSettings &amp;&amp; applicationSettings.CanEdit) {
        ///			var firstTimeEdit = new DMH.FirstTimeEdit();
        ///			firstTimeEdit.Initialize(applicationSettings, page);
        ///		}
        ///
        ///		var helpButton = new DMH.HelpButton();
        ///		helpBut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeViewInjectedScripts {
            get {
                return ResourceManager.GetString("Html_FirstTimeViewInjectedScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/help.axd?m=JavaScript&quot; type=&quot;application/javascript&quot;&gt;&lt;/script&gt;&lt;script type=&quot;application/javascript&quot;&gt;var applicationSettings=[APPLICATIONSETTINGSJSON];var page=[PAGEJSON];var userPageSettings=[USERPAGESETTINGSJSON];$(function(){var firstTimeEdit;if(applicationSettings&amp;&amp;applicationSettings.CanEdit){var firstTimeEdit=new DMH.FirstTimeEdit();firstTimeEdit.Initialize(applicationSettings,page);}
        ///var helpButton=new DMH.HelpButton();helpButton.Initialize(firstTimeEdit,page);var firstTimeView;firstTime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeViewInjectedScripts_min {
            get {
                return ResourceManager.GetString("Html_FirstTimeViewInjectedScripts_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @nextId INT 
        ///SELECT @nextId = ISNULL(MAX(Id), 0) + 1 FROM DocmahBullets
        ///
        ///INSERT INTO [DocmahBullets] (
        ///	Id
        ///	,[PageId]
        ///	,[Number]
        ///	,[Text]
        ///	,[VerticalOffset]
        ///	,[HorizontalOffset]
        ///	,[OffsetElementId]
        ///	,[DocVerticalOffset]
        ///	,[DocHorizontalOffset]
        ///)
        ///VALUES (
        ///	@nextId
        ///	,@pageId
        ///	,@number
        ///	,@text
        ///	,@verticalOffset
        ///	,@horizontalOffset
        ///	,@offsetElementId
        ///	,@docVerticalOffset
        ///	,@docHorizontalOffset
        ///)
        ///
        ///SELECT @nextId.
        /// </summary>
        internal static string Sql_Bullet_Create {
            get {
                return ResourceManager.GetString("Sql_Bullet_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE [DocmahBullets] WHERE Id = @id
        ///.
        /// </summary>
        internal static string Sql_Bullet_Delete {
            get {
                return ResourceManager.GetString("Sql_Bullet_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE [DocmahBullets] 
        ///WHERE PageId = @pageId.
        /// </summary>
        internal static string Sql_Bullet_DeleteByPageId {
            get {
                return ResourceManager.GetString("Sql_Bullet_DeleteByPageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF( (SELECT COUNT(*) FROM DocmahBullets WHERE Id = {0}) = 1)BEGIN
        ///	UPDATE DocmahBullets SET PageId = {1},Number = {2},Text = {3},VerticalOffset = {4},HorizontalOffset = {5},OffsetElementId = {6},DocVerticalOffset = {7},DocHorizontalOffset = {8} WHERE Id = {0}
        ///END ELSE BEGIN
        ///	INSERT DocmahBullets(Id,PageId,Number,Text,VerticalOffset,HorizontalOffset,OffsetElementId,DocVerticalOffset,DocHorizontalOffset) VALUES ({0},{1},{2},{3},{4},{5},{6},{7},{8})
        ///END
        ///.
        /// </summary>
        internal static string Sql_Bullet_Install {
            get {
                return ResourceManager.GetString("Sql_Bullet_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM DocmahBullets
        ///.
        /// </summary>
        internal static string Sql_Bullet_ReadAll {
            get {
                return ResourceManager.GetString("Sql_Bullet_ReadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM DocmahBullets
        ///WHERE PageId = @pageId.
        /// </summary>
        internal static string Sql_Bullet_ReadByPageId {
            get {
                return ResourceManager.GetString("Sql_Bullet_ReadByPageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [DocmahBullets]
        ///   SET [PageId] = @pageId
        ///      ,[Number] = @number
        ///      ,[Text] = @text
        ///      ,[VerticalOffset] = @verticalOffset
        ///      ,[HorizontalOffset] = @horizontalOffset
        ///      ,[OffsetElementId] = @offsetElementId
        ///	  ,[DocVerticalOffset] = @docVerticalOffset
        ///	  ,[DocHorizontalOffset] = @docHorizontalOffset
        /// WHERE Id = @id.
        /// </summary>
        internal static string Sql_Bullet_Update {
            get {
                return ResourceManager.GetString("Sql_Bullet_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- If the configuration table doesn&apos;t exist, return 0.
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[DocmahConfiguration]&apos;) AND type in (N&apos;U&apos;)) BEGIN
        ///	SELECT 0;
        ///END
        ///
        ///SELECT [Value] FROM [DocmahConfiguration] WHERE [Name] = @name;
        ///.
        /// </summary>
        internal static string Sql_Configuration_Read {
            get {
                return ResourceManager.GetString("Sql_Configuration_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [DocmahConfiguration]
        ///SET [Value] = @value
        ///WHERE [Name] = @name.
        /// </summary>
        internal static string Sql_Configuration_Update {
            get {
                return ResourceManager.GetString("Sql_Configuration_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///CREATE TABLE [dbo].[DocmahBullets](
        ///	[Id] [int] NOT NULL,
        ///	[PageId] [int] NOT NULL,
        ///	[Number] [int] NOT NULL,
        ///	[Text] [nvarchar](max) NOT NULL,
        ///	[VerticalOffset] [int] NOT NULL,
        ///	[HorizontalOffset] [int] NOT NULL,
        ///	[OffsetElementId] [nvarchar](50) NOT NULL,
        ///	[DocVerticalOffset] [int] NULL,
        ///	[DocHorizontalOffset] [int] NULL,
        /// CONSTRAINT [PK_DocmahBullets] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC
        ///)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
        ///)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Database_01 {
            get {
                return ResourceManager.GetString("Sql_Database_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @databaseName NVARCHAR(128)
        ///SET @databaseName = &apos;DocmahUnitTests&apos;
        ///
        ///IF (
        ///	EXISTS(
        ///		SELECT name 
        ///		FROM master.dbo.sysdatabases 
        ///		WHERE &apos;[&apos; + name + &apos;]&apos; = &apos;DocmahUnitTests&apos;
        ///			OR name = &apos;DocmahUnitTests&apos;
        ///	)
        ///) BEGIN
        ///	DROP DATABASE DocmahUnitTests
        ///END
        ///
        ///CREATE DATABASE DocmahUnitTests
        ///.
        /// </summary>
        internal static string Sql_Database_Create {
            get {
                return ResourceManager.GetString("Sql_Database_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @databaseName NVARCHAR(128)
        ///IF (
        ///	EXISTS(
        ///		SELECT name 
        ///		FROM master.dbo.sysdatabases 
        ///		WHERE &apos;[&apos; + name + &apos;]&apos; = &apos;DocmahUnitTests&apos;
        ///			OR name = &apos;DocmahUnitTests&apos;
        ///	)
        ///) BEGIN
        ///	ALTER DATABASE DocmahUnitTests SET SINGLE_USER WITH ROLLBACK IMMEDIATE
        ///
        ///	DROP DATABASE DocmahUnitTests
        ///END.
        /// </summary>
        internal static string Sql_Database_Drop {
            get {
                return ResourceManager.GetString("Sql_Database_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Need to fake identity column so that Ids generated when writing documentation
        ///-- are used in production so that installation scripts can update help 
        ///-- without invalidating user settings.
        ///
        ///DECLARE @nextId INT 
        ///SELECT @nextId = ISNULL(MAX(Id), 0) + 1 FROM DocmahPages
        ///
        ///INSERT INTO [DocmahPages] (
        ///	[Id]
        ///	,[PageTypeId]
        ///	,[ParentPageId]
        ///	,[Order]
        ///	,[SourceUrl]
        ///	,[Title]
        ///	,[Content]
        ///	,[VerticalOffset]
        ///	,[HorizontalOffset]
        ///	,[OffsetElementId]
        ///	,[DocImageUrl]
        ///	,[DocVerticalOffset]
        ///	,[DocHori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Page_Create {
            get {
                return ResourceManager.GetString("Sql_Page_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE [DocmahPages]
        ///WHERE Id = @id.
        /// </summary>
        internal static string Sql_Page_Delete {
            get {
                return ResourceManager.GetString("Sql_Page_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT 1 FROM DocmahPages WHERE Id = {0}) BEGIN 
        ///	UPDATE DocmahPages SET PageTypeId = {1},ParentPageId = {2},[Order] = {3},SourceUrl = {4},Title = {5},Content = {6},VerticalOffset = {7},HorizontalOffset = {8},OffsetElementId = {9},DocImageUrl = {10},DocVerticalOffset = {11},DocHorizontalOffset = {12},IsHidden = {13} WHERE Id = {0}
        ///END ELSE BEGIN
        ///	INSERT DocmahPages(Id,PageTypeId,ParentPageId,[Order],SourceUrl,Title,Content,VerticalOffset,HorizontalOffset,OffsetElementId,DocImageUrl,DocVertical [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Page_Install {
            get {
                return ResourceManager.GetString("Sql_Page_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH Pages_CTE
        ///AS (
        ///	SELECT 
        ///		1 AS [Level],
        ///		[Id],
        ///		[ParentPageId],
        ///		[Order]
        ///	FROM [DocmahPages]
        ///	WHERE ParentPageId IS NULL
        ///
        ///	UNION ALL
        ///
        ///	SELECT 
        ///		[Parent].[Level] + 1 AS [Level],
        ///		[Page].[Id],
        ///		[Page].[ParentPageId],
        ///		[Page].[Order]
        ///	FROM [DocmahPages] AS [Page]
        ///		JOIN Pages_CTE AS Parent ON [Page].ParentPageId = Parent.Id
        ///)
        ///SELECT Pages.*
        ///FROM DocmahPages AS Pages
        ///	JOIN Pages_CTE AS Cte ON Pages.Id = Cte.Id
        ///ORDER BY Cte.[Level],Cte.[Order].
        /// </summary>
        internal static string Sql_Page_ReadAll {
            get {
                return ResourceManager.GetString("Sql_Page_ReadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM [DocmahPages]
        ///WHERE Id = @id.
        /// </summary>
        internal static string Sql_Page_ReadById {
            get {
                return ResourceManager.GetString("Sql_Page_ReadById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT *
        ///FROM [DocmahPages]
        ///WHERE ISNULL(@parentId, -1) = ISNULL(ParentPageId, -1)
        ///ORDER BY [Order]
        ///.
        /// </summary>
        internal static string Sql_Page_ReadByParentId {
            get {
                return ResourceManager.GetString("Sql_Page_ReadByParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @hitCount INT
        ///
        ///SELECT @hitCount = COUNT(*)
        ///FROM DocmahPageUrls
        ///WHERE @url = Url
        ///
        ///IF @hitCount &gt; 0 BEGIN	
        ///	SELECT P.*
        ///	FROM DocmahPages AS P
        ///		JOIN DocmahPageUrls AS U ON U.PageId = P.Id
        ///	WHERE @url = U.Url
        ///END ELSE BEGIN
        ///	SELECT P.*
        ///	FROM DocmahPages AS P
        ///		JOIN DocmahPageUrls AS U ON U.PageId = P.Id
        ///	WHERE @url LIKE U.Url
        ///END.
        /// </summary>
        internal static string Sql_Page_ReadByUrl {
            get {
                return ResourceManager.GetString("Sql_Page_ReadByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH Pages_CTE
        ///AS (
        ///	SELECT 
        ///		1 AS [Level],
        ///		[Id],[ParentPageId],[Order],[Title],[IsHidden]
        ///	FROM [DocmahPages]
        ///	WHERE ParentPageId IS NULL
        ///		AND (@includeHidden = 1 OR [IsHidden] = 0)
        ///
        ///	UNION ALL
        ///
        ///	SELECT 
        ///		[Parent].[Level] + 1 AS [Level],
        ///		[Page].[Id],[Page].[ParentPageId],[Page].[Order],[Page].[Title],[Page].[IsHidden]
        ///	FROM [DocmahPages] AS [Page]
        ///		JOIN Pages_CTE AS Parent ON [Page].ParentPageId = Parent.Id
        ///	WHERE @includeHidden = 1 OR [Page].[IsHidden] = 0
        ///)
        ///SELECT [Id],[ParentPa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Page_ReadTableOfContents {
            get {
                return ResourceManager.GetString("Sql_Page_ReadTableOfContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [DocmahPages]
        ///   SET [PageTypeId] = @pageTypeId
        ///      ,[ParentPageId] = @parentPageId
        ///      ,[Order] = @order
        ///      ,[SourceUrl] = @sourceUrl
        ///      ,[Title] = @title
        ///      ,[Content] = @content
        ///      ,[VerticalOffset] = @verticalOffset
        ///      ,[HorizontalOffset] = @horizontalOffset
        ///      ,[OffsetElementId] = @offsetElementId
        ///	  ,[DocImageUrl] = @docImageUrl
        ///	  ,[DocVerticalOffset] = @docVerticalOffset
        ///	  ,[DocHorizontalOffset] = @docHorizontalOffset
        ///	  ,[IsHidden] = @isHidden
        /// WHERE Id = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Page_Update {
            get {
                return ResourceManager.GetString("Sql_Page_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [DocmahPageUrls] (
        ///	[Url]
        ///	,[PageId]
        ///) VALUES (
        ///	@url
        ///	,@pageId
        ///).
        /// </summary>
        internal static string Sql_PageUrl_Create {
            get {
                return ResourceManager.GetString("Sql_PageUrl_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE DocmahPageUrls
        ///WHERE PageId = @pageId.
        /// </summary>
        internal static string Sql_PageUrl_DeleteByPageId {
            get {
                return ResourceManager.GetString("Sql_PageUrl_DeleteByPageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM DocmahPageUrls
        ///WHERE PageId = @pageId.
        /// </summary>
        internal static string Sql_PageUrl_ReadByPageId {
            get {
                return ResourceManager.GetString("Sql_PageUrl_ReadByPageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [DocmahUserPageSettings](
        ///	[UserName]
        ///	,[PageId]
        ///	,[HidePage]
        ///)
        ///OUTPUT Inserted.ID
        ///VALUES (
        ///	 @userName
        ///	,@pageId
        ///	,@hidePage
        ///).
        /// </summary>
        internal static string Sql_UserPageSettings_Create {
            get {
                return ResourceManager.GetString("Sql_UserPageSettings_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM DocmahUserPageSettings
        ///WHERE 
        ///	UserName = @userName 
        ///	AND PageId = @pageId.
        /// </summary>
        internal static string Sql_UserPageSettings_ReadByUserAndPage {
            get {
                return ResourceManager.GetString("Sql_UserPageSettings_ReadByUserAndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [DocmahUserPageSettings]
        ///   SET [UserName] = @userName
        ///      ,[PageId] = @pageId
        ///      ,[HidePage] = @hidePage
        /// WHERE Id = @id.
        /// </summary>
        internal static string Sql_UserPageSettings_Update {
            get {
                return ResourceManager.GetString("Sql_UserPageSettings_Update", resourceCulture);
            }
        }
    }
}
