//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocMAH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocMAH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** Namespace **/
        ///var DMH = DMH || {};
        ///
        ////** Constants and Singletons **/
        ///DMH.PageTypes = function () {
        ///
        ///	//** Public Fields **
        ///	this.FirstTimePage = 1;
        ///	this.DocumentationPage = 2;
        ///
        ///	// Return singleton.
        ///	return this;
        ///}();
        ///
        ///DMH.HistoryState = function () {
        ///	this.Replace = 1;
        ///	this.Push = 2;
        ///	this.Pop = 3;
        ///
        ///	return this;
        ///}();
        ///
        ///DMH.Urls = function () {
        ///
        ///	// ** Public Fields **
        ///	this.DeletePage = &apos;/help.axd?m=DeletePage&apos;;
        ///	this.GenerateInstallScript = &apos;/help.axd?m=GenerateInstallScrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHJavaScript {
            get {
                return ResourceManager.GetString("DocMAHJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var DMH=DMH||{};DMH.PageTypes=function(){return this.FirstTimePage=1,this.DocumentationPage=2,this}();DMH.HistoryState=function(){return this.Replace=1,this.Push=2,this.Pop=3,this}();DMH.Urls=function(){return this.DeletePage=&quot;/help.axd?m=DeletePage&quot;,this.GenerateInstallScript=&quot;/help.axd?m=GenerateInstallScript&quot;,this.MovePage=&quot;/help.axd?m=MovePage&quot;,this.NavigateDocumentation=&quot;/help.axd?m=DocumentationPage&quot;,this.ReadApplicationSettings=&quot;/help.axd?m=ReadApplicationSettings&quot;,this.ReadPage=&quot;/help.axd?m=ReadPage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHJavaScript_min {
            get {
                return ResourceManager.GetString("DocMAHJavaScript_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* comment to fix less compiling (https://github.com/madskristensen/WebEssentials2013/issues/1696)*/
        ////******	Custom JSTree Node Icons ******/
        ///.jstree-default .jstree-node.jstree-closed &gt; i.jstree-icon {
        ///  background-image: url(&apos;data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHStyles {
            get {
                return ResourceManager.GetString("DocMAHStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jstree-default .jstree-node.jstree-closed&gt;i.jstree-icon{background-image:url(&apos;data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkNhcGFfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHStyles_min {
            get {
                return ResourceManager.GetString("DocMAHStyles_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link href=&quot;/help.axd?m=CSS&quot; rel=&quot;stylesheet&quot; /&gt;.
        /// </summary>
        internal static string Html_CssLink {
            get {
                return ResourceManager.GetString("Html_CssLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;dmh-&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;[TITLE]&lt;/title&gt;
        ///	[JSTREECSS]
        ///	&lt;link href=&quot;/help.axd?m=CSS&quot; rel=&quot;stylesheet&quot; /&gt;
        ///	[CUSTOMCSS]
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div id=&quot;dmhDocToolBar&quot;&gt;
        ///		&lt;h3&gt;Edit Tools&lt;/h3&gt;
        ///		&lt;div class=&quot;dmhButtonBar&quot;&gt;
        ///			&lt;div id=&quot;dmhGenerateInstallScriptButton&quot; class=&quot;dmhButton dmhButtonSmall&quot;&gt;Generate Install Scripts&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;dmhDocToolBarBreak&quot;&gt;&lt;/div&gt;
        ///		&lt;div id=&quot;dmhStatusBar&quot;&gt;
        ///			&lt;div id=&quot;dmhStatusMessage&quot;&gt;&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div id=&quot;dmhCommonTools&quot;&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Documentation {
            get {
                return ResourceManager.GetString("Html_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html class=&quot;dmh-&quot;&gt;&lt;head&gt;&lt;title&gt;[TITLE]&lt;/title&gt;[JSTREECSS]&lt;link href=&quot;/help.axd?m=CSS&quot; rel=&quot;stylesheet&quot;&gt;[CUSTOMCSS]&lt;/head&gt;&lt;body&gt;&lt;div id=&quot;dmhDocToolBar&quot;&gt;&lt;h3&gt;Edit Tools&lt;/h3&gt;&lt;div class=&quot;dmhButtonBar&quot;&gt;&lt;div id=&quot;dmhGenerateInstallScriptButton&quot; class=&quot;dmhButton dmhButtonSmall&quot;&gt;Generate Install Scripts&lt;/div&gt;&lt;/div&gt;&lt;div id=&quot;dmhDocToolBarBreak&quot;&gt;&lt;/div&gt;&lt;div id=&quot;dmhStatusBar&quot;&gt;&lt;div id=&quot;dmhStatusMessage&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;div id=&quot;dmhCommonTools&quot;&gt;&lt;div class=&quot;dmhFormRow&quot;&gt;&lt;label for=&quot;dmhIsHidden&quot;&gt;Hide Page&lt;/label&gt; &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Documentation_min {
            get {
                return ResourceManager.GetString("Html_Documentation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhCreateHelpButton&quot; class=&quot;dmh- dmhButton&quot;&gt;Create Help Page&lt;/div&gt;
        ///&lt;div id=&quot;dmhFirstTimeEdit&quot; class=&quot;dmh- dmhDialog&quot;&gt;
        ///	&lt;div class=&quot;dmhDialogTitle&quot;&gt;Create Help Page&lt;/div&gt;
        ///	&lt;div class=&quot;dmhDialogContent&quot;&gt;
        ///		&lt;div class=&quot;dmhFormRow&quot;&gt;
        ///			&lt;label for=&quot;dmhFirstTimeEditTitle&quot;&gt;Help Title&lt;/label&gt;
        ///			&lt;input id=&quot;dmhFirstTimeEditTitle&quot; type=&quot;text&quot; /&gt;
        ///			&lt;div class=&quot;dmhFieldHelp&quot;&gt;Required&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div class=&quot;dmhFormRow&quot;&gt;
        ///			&lt;label for=&quot;dmhFirstTimeEditMatchUrls&quot;&gt;Match Urls&lt;/label&gt;
        ///			&lt;input id= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeEdit {
            get {
                return ResourceManager.GetString("Html_FirstTimeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhCreateHelpButton&quot; class=&quot;dmh- dmhButton&quot;&gt;Create Help Page&lt;/div&gt;&lt;div id=&quot;dmhFirstTimeEdit&quot; class=&quot;dmh- dmhDialog&quot;&gt;&lt;div class=&quot;dmhDialogTitle&quot;&gt;Create Help Page&lt;/div&gt;&lt;div class=&quot;dmhDialogContent&quot;&gt;&lt;div class=&quot;dmhFormRow&quot;&gt;&lt;label for=&quot;dmhFirstTimeEditTitle&quot;&gt;Help Title&lt;/label&gt; &lt;input id=&quot;dmhFirstTimeEditTitle&quot; type=&quot;text&quot;&gt;&lt;div class=&quot;dmhFieldHelp&quot;&gt;Required&lt;/div&gt;&lt;/div&gt;&lt;div class=&quot;dmhFormRow&quot;&gt;&lt;label for=&quot;dmhFirstTimeEditMatchUrls&quot;&gt;Match Urls&lt;/label&gt; &lt;input id=&quot;dmhFirstTimeEditMatchUrls&quot; type=&quot;text&quot;&gt;&lt;div  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeEdit_min {
            get {
                return ResourceManager.GetString("Html_FirstTimeEdit_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhModalMask&quot; class=&quot;dmh-&quot;&gt;&lt;/div&gt;
        ///&lt;div id=&quot;dmhFirstTimeView&quot; class=&quot;dmh- dmhDialog&quot;&gt;
        ///	&lt;div&gt;
        ///		&lt;div id=&quot;dmhShowDocumentationButton&quot; title=&quot;View full documentation&quot;&gt;
        ///			&lt;svg version=&quot;1.1&quot; id=&quot;dmhDocumentationIcon&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; x=&quot;0px&quot; y=&quot;0px&quot; width=&quot;50px&quot;
        ///				 height=&quot;50px&quot; viewBox=&quot;0 0 50 50&quot; enable-background=&quot;new 0 0 50 50&quot; xml:space=&quot;preserve&quot;&gt;
        ///			&lt;g id=&quot;_x38_7&quot;&gt;
        ///			&lt;g&gt;
        ///			&lt;path d=&quot;M12.03,21.967c-1.318,0-1.318,2.047,0,2.047c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeView {
            get {
                return ResourceManager.GetString("Html_FirstTimeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;dmhModalMask&quot; class=&quot;dmh-&quot;&gt;&lt;/div&gt;&lt;div id=&quot;dmhFirstTimeView&quot; class=&quot;dmh- dmhDialog&quot;&gt;&lt;div&gt;&lt;div id=&quot;dmhShowDocumentationButton&quot; title=&quot;View full documentation&quot;&gt;&lt;svg version=&quot;1.1&quot; id=&quot;dmhDocumentationIcon&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; x=&quot;0px&quot; y=&quot;0px&quot; width=&quot;50px&quot; height=&quot;50px&quot; viewBox=&quot;0 0 50 50&quot; enable-background=&quot;new 0 0 50 50&quot; xml:space=&quot;preserve&quot;&gt;&lt;g id=&quot;_x38_7&quot;&gt;&lt;g&gt;&lt;path d=&quot;M12.03,21.967c-1.318,0-1.318,2.047,0,2.047c5.249,0,10.497,0,15.746,0c1.319,0,1.319-2.047,0-2.047
        ///												C22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeView_min {
            get {
                return ResourceManager.GetString("Html_FirstTimeView_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/help.axd?m=JavaScript&quot; type=&quot;application/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&quot;application/javascript&quot;&gt;
        ///	var applicationSettings = [APPLICATIONSETTINGSJSON];
        ///	var page = [PAGEJSON];
        ///	var userPageSettings = [USERPAGESETTINGSJSON];
        ///	$(function () {
        ///		var firstTimeEdit;
        ///		if (applicationSettings &amp;&amp; applicationSettings.CanEdit) {
        ///			var firstTimeEdit = new DMH.FirstTimeEdit();
        ///			firstTimeEdit.Initialize(applicationSettings, page);
        ///		}
        ///
        ///		var helpButton = new DMH.HelpButton();
        ///		helpBut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeViewInjectedScripts {
            get {
                return ResourceManager.GetString("Html_FirstTimeViewInjectedScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/help.axd?m=JavaScript&quot; type=&quot;application/javascript&quot;&gt;&lt;/script&gt;&lt;script type=&quot;application/javascript&quot;&gt;var applicationSettings=[APPLICATIONSETTINGSJSON];var page=[PAGEJSON];var userPageSettings=[USERPAGESETTINGSJSON];$(function(){var firstTimeEdit;if(applicationSettings&amp;&amp;applicationSettings.CanEdit){var firstTimeEdit=new DMH.FirstTimeEdit();firstTimeEdit.Initialize(applicationSettings,page);}
        ///var helpButton=new DMH.HelpButton();helpButton.Initialize(firstTimeEdit,page);var firstTimeView;firstTime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_FirstTimeViewInjectedScripts_min {
            get {
                return ResourceManager.GetString("Html_FirstTimeViewInjectedScripts_min", resourceCulture);
            }
        }
    }
}
