//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocMAH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocMAH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** Namespace **/
        ///var DMH = DMH || {};
        ///
        ////** Constants and Singletons **/
        ///DMH.PageTypes = function () {
        ///
        ///	//** Public Fields **
        ///	this.FirstTimePage = 1;
        ///	this.DocumentationPage = 2;
        ///
        ///	// Return singleton.
        ///	return this;
        ///}();
        ///
        ///DMH.HistoryState = function () {
        ///	this.Replace = 1;
        ///	this.Push = 2;
        ///	this.Pop = 3;
        ///
        ///	return this;
        ///}();
        ///
        ///DMH.Urls = function () {
        ///
        ///	// ** Public Fields **
        ///	this.DeletePage = &apos;/help.axd?m=DeletePage&apos;;
        ///	this.GenerateInstallScript = &apos;/help.axd?m=GenerateInstallScrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHJavaScript {
            get {
                return ResourceManager.GetString("DocMAHJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var DMH=DMH||{};DMH.PageTypes=function(){return this.FirstTimePage=1,this.DocumentationPage=2,this}();DMH.HistoryState=function(){return this.Replace=1,this.Push=2,this.Pop=3,this}();DMH.Urls=function(){return this.DeletePage=&quot;/help.axd?m=DeletePage&quot;,this.GenerateInstallScript=&quot;/help.axd?m=GenerateInstallScript&quot;,this.MovePage=&quot;/help.axd?m=MovePage&quot;,this.NavigateDocumentation=&quot;/help.axd?m=DocumentationPage&quot;,this.ReadApplicationSettings=&quot;/help.axd?m=ReadApplicationSettings&quot;,this.ReadPage=&quot;/help.axd?m=ReadPage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHJavaScript_min {
            get {
                return ResourceManager.GetString("DocMAHJavaScript_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* comment to fix less compiling (https://github.com/madskristensen/WebEssentials2013/issues/1696)*/
        ////******	Custom JSTree Node Icons ******/
        ///.jstree-default .jstree-node.jstree-closed &gt; i.jstree-icon {
        ///  background-image: url(&apos;data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHStyles {
            get {
                return ResourceManager.GetString("DocMAHStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jstree-default .jstree-node.jstree-closed&gt;i.jstree-icon{background-image:url(&apos;data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkNhcGFfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocMAHStyles_min {
            get {
                return ResourceManager.GetString("DocMAHStyles_min", resourceCulture);
            }
        }
    }
}
